project:
  type: book
  output-dir: site

book:
  title: "Understanding Deep Learning"
  author: "Ali Bozkoyun"
  chapters:
    - text: Welcome
      href: index.qmd
    - part: Beginner
      chapters:
        - text: Perceptron
          href: docs/beginner/Perceptron.ipynb
        - text: Gradient Descent Fundamentals
          href: docs/beginner/gradient_descent/01_gd_fundamentals.ipynb
        - text: SGD and Other Optimizers
          href: docs/beginner/gradient_descent/02_sgd_and_others.ipynb
        - text: Logistic Perceptron
          href: docs/beginner/Logistic_perceptron.ipynb

  sidebar:
    style: docked
    search: true
    collapse-level: 3
    tools:
      - icon: github
        href: https://github.com/red-apple38/understanding-deep-learning
        aria-label: GitHub repository
    contents:
      - text: Welcome
        href: index.qmd
      - section: Beginner
        contents:
          - text: Perceptron
            href: docs/beginner/Perceptron.ipynb
          - section: Gradient Descent
            contents:
              - text: Gradient Descent Fundamentals
                href: docs/beginner/gradient_descent/01_gd_fundamentals.ipynb
              - text: SGD and Other Optimizers
                href: docs/beginner/gradient_descent/02_sgd_and_others.ipynb
          - text: Logistic Perceptron
            href: docs/beginner/Logistic_perceptron.ipynb

execute:
  freeze: false

format:
  html:
    theme: cosmo
    toc: true
    code-fold: show
    number-sections: false

